const UIcolorPallete = {
    'whity-gray': "#F9F9F9",
    dark: "#30333D",
    brown: "#333333",
    graydark: "#707D88",
    gray: "#C3CAD5", /* Gray_middle */
    graylight: "#EAECEF",
    green: "#4CDB96",
    red: "#EB5757",
    orange: "#F2994A",
    yellow: "#F2C94C",
    blue: "#3176FA",
    bluedark: "#0158FF",
    bluedarker: "#043590",
    white: "#fff",
    'dark-overlay': 'rgba(48,51,61, 0.5)',
    'blued-white': "#f9fbff"
};

const IconSizes = {
    'icon-sm': '10px',
    'icon-md': '18px',
    'icon-lg': '32px'
}

const PointerInputSizes = {
    'checkbox': '20px'
}

const SVGcolorProps = Object.assign({}, {
    'current': 'currentColor',
    'none': 'none'
}, UIcolorPallete);

module.exports = {
    prefix: '',
    important: false,
    separator: ':',
    variants: {
        fill: ['hover'],
        stroke: ['hover']
    },
    theme: {
        extend: {
            maxWidth: {
                '1150px': '1150px',
                '1320px': '1320px',
                '840px': '840px',
                '730px': '730px',
                '320px': '320px',
                'thumb': '64px',
                'icon': '40px'
            },
            minWidth: {
                'input-panel': '230px',
                'time-input-panel': '85px',
                'switcher': '48px',
                'period-input-panel': '148px',
                'tip': '170px',
                'reg-card': '350px',
                'modal': '350px',
                'marketcard': '240px',
                'input-md': '310px',
                'preview': '60px',
            },
            minHeight: {
                '1/6v': '16vh',
                'textarea': '100px',
                'menu-row': '30px',
                'filedropping': '500px'
            },
            maxHeight: {
                'textarea': '500px',
                'thumb': '64px'
            },
            width: Object.assign({
                'dot': '8px',
                '1/1': '100%',
                '1/5': '20%',
                'inherit': 'inherit',
                'c-nav-group': '80px',
                'c-day-cell': '40px',
                'btn-iconed': '40px',
                'btn-iconed-thin': '32px',
                'switcher': '48px',
                'switch-dot': '24px',
                'tip-arrow': '15px',
                'calendar': '330px',
                'sidebar-short': '52px',
                'sidebar-full': '200px',
                'sidebar-logo': '110px',
                'step-circle': '32px',
                'dash': '12px',
            }, IconSizes, PointerInputSizes),
            height: Object.assign({
                'dot': '8px',
                'c-day-cell': '40px',
                'btn-base': '40px',
                'input-panel': '40px',
                'btn-thin': '32px',
                'switcher': '28px',
                'switch-dot': '24px',
                'tip-arrow': '15px',
                'screen': '100vh',
                'header': '60px',
                'sidebar-logo': '22px',
                'step-circle': '32px',
                'dash': '4px',
                '1/5': '20%',
                '1/4': '25%',
                '1/2': '50%',
                '3/4': '75%',
                '4/5': '80%',
                "dashboard-panel": '610px',
                'layout-wrapper-footed': 'calc(100% - 64px)',
                'layout-section-headed': "calc(100vh - 60px)",
                'layout-section-footed': "calc(100vh - 60px - 64px)"
            }, IconSizes, PointerInputSizes),
            colors: {
                ui: UIcolorPallete
            },
            boxShadow: {
                sm: "0px 2px 8px rgba(42, 85, 150, 0.2)",
                md: "0 4px 16px rgba(42, 85, 150, 0.2)",
                'md-blue': "0 4px 16px rgba(21, 157, 255, 0.25)",
                lg: "0px 2px 32px rgba(42, 85, 150, 0.2)",
                'md-blue': '0 4px 16px rgba(21, 157, 255, 0.25)',
                'lg-blue': '0 2px 32px rgba(21, 157, 255, 0.25)',
                'md-red': '0px 4px 16px rgba(235, 87, 87, 0.25)'
            },
            borderRadius: {
                select: '20px',
                tip: '10px',
                alert: '80px'
            },
            inset: {
                '100': '100%',
                'tip-arrow': 'calc(100% - 7px)',
                'm90px': '-90px',
                'm75px': '-75px',
                'm60px': '-60px',
                'm40px': '-40px',
                'm30px': '-30px',
                'm20px': '-20px',
                'm15px': '-15px',
                'm5px': '-5px',
                '20px': '20px',
                '25px': '25px'
            },
            fontSize: {
                'xs': '9px',
                'sm': '12px',
                'md': '14px',
                'lg': '18px',
                'xl': '24px',
                'xxl': '36px'
            },
            flexGrow: {
                '2': '2'
            },
            zIndex: {
                '1': '1',
                '2': '2',
                '100': '100'
            },
            opacity: {
                '10': '0.1'
            }
        },
        fill: SVGcolorProps,
        stroke: SVGcolorProps,
        transform: { // defaults to this value
            'none': 'none',
        },
        transformOrigin: { // defaults to these values
            'radiopoint': '40% 40%',
            'center': '50% 50%',
            't': 'top',
            'tr': 'top right',
            'r': 'right',
            'br': 'bottom right',
            'b': 'bottom',
            'bl': 'bottom left',
            'l': 'left',
            'tl': 'top left',
        },
        translate: { // defaults to {}
            'switch-dot': '80%',
            '1/2': '50%',
            'full': '100%',
            'right-up': ['100%', '-100%'],
            '3d': ['40px', '-60px', '-130px'],
        },
        scale: { // defaults to {}
            '50': '0.5',
            '60': '0.6',
            '70': '0.7',
            '80': '0.8',
            '80': '0.8',
            '90': '0.9',
            '100': '1',
            '110': '1.1',
            '150': '1.5',
            '-100': '-1',
            'stretched-x': ['2', '0.5'],
            'stretched-y': ['0.5', '2'],
            '3d': ['0.5', '1', '2'],
        },
        rotate: { // defaults to {}
        '0': '0',
        '45': '45deg',
        '135': '135deg',
        '225': '225deg',
        '90': '90deg',
        '180': '180deg',
        '270': '270deg',
        '360': '360deg',
        '3d': ['0', '1', '0.5', '45deg'],
        },
        transitionProperty: { // defaults to these values
            'none': 'none',
            'all': 'all',
            'color': 'color',
            'bg': 'background-color',
            'border': 'border-color',
            'colors': ['color', 'background-color', 'border-color'],
            'opacity': 'opacity',
            'transform': 'transform',
        },
        transitionDuration: { // defaults to these values
            'default': '250ms',
            '0': '0ms',
            '100': '100ms',
            '150': '150ms',
            '250': '250ms',
            '500': '500ms',
            '750': '750ms',
            '1000': '1000ms',
        },
        transitionTimingFunction: { // defaults to these values
            'default': 'ease',
            'linear': 'linear',
            'ease': 'ease',
            'ease-in': 'ease-in',
            'ease-out': 'ease-out',
            'ease-in-out': 'ease-in-out',
        },
        transitionDelay: { // defaults to these values
            'default': '0ms',
            '0': '0ms',
            '100': '100ms',
            '250': '250ms',
            '500': '500ms',
            '750': '750ms',
            '1000': '1000ms',
        },
        willChange: { // defaults to these values
            'auto': 'auto',
            'scroll': 'scroll-position',
            'contents': 'contents',
            'opacity': 'opacity',
            'transform': 'transform',
        },
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
        },
        colors: {
            transparent: 'transparent',
            black: '#000',
            white: '#fff',
          }
        },
        spacing: {
            px: '1px',
            '0': '0',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '8': '2rem',
            '10': '2.5rem',
            '12': '3rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '32': '8rem',
            '40': '10rem',
            '48': '12rem',
            '56': '14rem',
            '64': '16rem',
        },
        backgroundColor: theme => theme('colors'),
        backgroundPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
        },
        backgroundSize: {
            auto: 'auto',
            cover: 'cover',
            contain: 'contain',
        },
        borderColor: theme => ({
            ...theme('colors'),
            default: theme('colors.gray.300', 'currentColor'),
        }),
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            default: '0.25rem',
            lg: '0.5rem',
            full: '9999px',
        },
        borderWidth: {
            default: '1px',
            '0': '0',
            '2': '2px',
            '4': '4px',
            '8': '8px',
        },
        boxShadow: {
            default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
            outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
            none: 'none',
        },
        container: {},
        cursor: {
            auto: 'auto',
            default: 'default',
            pointer: 'pointer',
            wait: 'wait',
            text: 'text',
            move: 'move',
            'not-allowed': 'not-allowed',
        },
        flex: {
            '1': '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
        },
        flexGrow: {
            '0': '0',
            default: '1'
        },
        flexShrink: {
            '0': '0',
            default: '1',
        },
        fontFamily: {
            sans: [
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [
                'Georgia',
                'Cambria',
                '"Times New Roman"',
                'Times',
                'serif',
            ],
            mono: [
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
        },
        fontWeight: {
            light: '300',
            normal: '400',
            bold: '700',
        },
        height: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
        }),
        inset: {
            '0': '0',
            auto: 'auto'
        },
        letterSpacing: {
            tighter: '-0.05em',
            tight: '-0.025em',
            normal: '0',
            wide: '0.025em',
            wider: '0.05em',
            widest: '0.1em',
        },
        lineHeight: {
            none: '1',
            uibase: '1.3',
            bodytext: '1.6',
        },
        listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
        },
        margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
        }),
        maxHeight: {
            full: '100%',
            screen: '100vh',
        },
        maxWidth: {
            xs: '20rem',
            sm: '24rem',
            md: '28rem',
            lg: '32rem',
            xl: '36rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '56rem',
            '5xl': '64rem',
            '6xl': '72rem',
            full: '100%',
        },
        minHeight: {
            '0': '0',
            full: '100%',
            screen: '100vh',
        },
        minWidth: {
            '0': '0',
            full: '100%',
        },
        objectPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
        },
        opacity: {
            '0': '0',
            '25': '0.25',
            '50': '0.5',
            '75': '0.75',
            '100': '1',
        },
        order: {
            first: '-9999',
            last: '9999',
            none: '0',
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            '10': '10',
            '11': '11',
            '12': '12',
        },
        padding: theme => theme('spacing'),
        placeholderColor: theme => theme('colors'),
        stroke: {
            current: 'currentColor',
        },
        textColor: theme => theme('colors'),
        width: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            full: '100%',
            screen: '100vw',
        }),
        zIndex: {
            auto: 'auto',
            '0': '0',
            '10': '10',
            '20': '20',
            '30': '30',
            '40': '40',
            '50': '50'
        },
        plugins: [
            require('tailwindcss-transitions')(),
            require('tailwindcss-transforms')({
                '3d': false, // defaults to false
              }),
        ],
    }
